# Generated by Django 5.2.1 on 2025-05-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcm_app', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
